# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d30789fd236fae67a59584541e9bc838acbb962dae905f4c260a794d2f9a4bf3e88b3219f1e0a3ccefce23b095a1ca8701ad8588f64a9ff01fad81bc58ebb6ab

test:
  secret_key_base: 0be6c2c6fd32f75567b9932974af6c2042d328fb40b0e908dec4674b63732e2d88c85ee03d2fa060eafbb3ec378479701db820565e10da30bc397bf9118f8918

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
